services:
  app:
    build:
      context: .
      target: development
      dockerfile: Dockerfile
    ports:
      - "3030:3030" # Express server
      - "5173:5173" # Vite dev server
    volumes:
      - ./server:/app/server
      - ./client:/app/client
      # Optionally avoid overwriting node_modules in the container:
      - /app/server/node_modules
      - /app/client/node_modules
