services:
  app:
    build:
      context: .
      target: production
    restart: always
    ports:
      - "127.0.0.1:3030:3030"
    environment:
      - NODE_ENV=production
      - DATA_DIR=.data
      - PORT=3030
      - USER_AGENT="ContentLibrary/0.1"
      - OPEN_LIBRARY_API_URL=https://openlibrary.org
      - PODCAST_API_URL=https://api.podcastindex.org/api/1.0/
      - PODCAST_API_KEY=${PODCAST_API_KEY}
      - PODCAST_API_SECRET=${PODCAST_API_SECRET}
      - OMDB_API_URL=https://www.omdbapi.com
      - OMDB_API_KEY=${OMDB_API_KEY}
    networks:
      - web

networks:
  web:
    driver: bridge
