services:
  app:
    build:
      context: .
      target: production
    restart: always
    ports:
      - "127.0.0.1:3030:3030"
    environment:
      - NODE_ENV=production
    networks:
      - web

networks:
  web:
    driver: bridge
